### ISSUE TITLE
Configure -> Expert: warning about changing configurations overflow

### ISSUE THREAD

**Issue by braiam** [cdberkstresser/fah-control#11]
On the configure dialog, expert tab, the warning overflows. It probably lacks a container.

![image](https://user-images.githubusercontent.com/1323412/80311417-8cd3bc80-87ad-11ea-98d5-f8679245c313.png)

**Comment by cdberkstresser** [comment]
Good catch!  Fixed by commit 06c9085
Thanks @braiam !
