### ISSUE TITLE
Problem with FAHControl Ubuntu 20.04 Connection refused

### ISSUE THREAD

**Issue by alessiouw** [cdberkstresser/fah-control#24]
Hello guys,
I have an issue with my FAH Control.

I installed everything in my ubuntu 20.04 from the official website but the FAH Control, where I used this: https://github.com/cdberkstresser/fah-control.

The client is up and running and it is working fine, but the FAHControl is not working anymore (in fact, it worked the first time).

Now everytime I start the FAHControl I have the following error "ERROR on connection to localhost:36330: [Errno 111] Connection refused".

The firewall is inactive (ufw status: Status inactive).
![immagine](https://user-images.githubusercontent.com/51789665/172786642-595f7154-3c25-46ee-b34d-eda2cc123281.png)

I'm wondering, is there something that I have to fix in iptables or something? Thanks

**Comment by kbernhagen** [comment]
The client config.xml allow and allow-no-pass lists must both include 127.0.0.1

Stop the client service before manually changing config.xml

**Comment by alessiouw** [comment]
Thank you! Solved it.
Took the sample config from  /usr/share/doc/fahclient/sample-config.xml
Killed all the "fah" processes. Changing the config.xml, started the FAHClient service and then the FAHControl and now it is working. 
Bye
