### ISSUE TITLE
python3 fahcontrol

### ISSUE THREAD

**Issue by bollix47** [cdberkstresser/fah-control#25]
I was able to get this running on 20.04 but for reasons unknown to me I can't get it running on 22.04 ... can you please confirm that is the expected behaviour and will there be an update?
FAHControl
Traceback (most recent call last):
  File "/usr/bin/FAHControl", line 25, in <module>
    from fah import FAHControl, load_fahcontrol_db
  File "/usr/lib/python3/dist-packages/fah/__init__.py", line 25, in <module>
    from . import util
  File "/usr/lib/python3/dist-packages/fah/util/__init__.py", line 24, in <module>
    from .OrderedDict import *
  File "/usr/lib/python3/dist-packages/fah/util/OrderedDict.py", line 23, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by SaschaVasarrhelyi** [comment]
I have the same Problem with Ubuntu- Mate 22.04LTS and Python 3.10

**Comment by SaschaVasarrhelyi** [comment]
In my case it workt after i download the master.zip from here extract it and run the "setup.py".
"python3 setup.py" or "python setup.py" from an console in the Directory you extract the Master zip from this reop.
Wish You a nice WE

**Comment by phisp** [comment]
I had the same issue with python3.10 and i solved it with:

within the file "/usr/lib/python3/dist-packages/fah/util/OrderedDict.py" 
replace 
`from collections import MutableMapping as DictMixin`
with

```
import sys
if sys.version_info[:2] >= (3, 8):
    from collections.abc import MutableMapping as DictMixin
else:
    from collections import MutableMapping as DictMixin
```

save and it works "FAHControl"

**Comment by cdberkstresser** [comment]
Incorporated into commit f2a52522cde95d588ddf5f641e7cd8502bccbbe6
