### ISSUE TITLE
Window size not saving after changing

### ISSUE THREAD

**Issue by gitHu6-newb** [cdberkstresser/fah-control#26]
Hi! Thanks so much for making a python 3 version! I have to ask, is this still supported or has a different fork superseded this one?

Symptom: after resizing the  FAHControl window to my liking and closing it, it will open with the default values again.

Is there a way I can edit something in a file somewhere to put my own width and height? I found the defaults in the FAHControl.glade file, but that's in the zip file before installation. If I can't edit something in my current installation, will altering that file with my own values and then recompiling and installing that do the trick?
Thanks

**Comment by cdberkstresser** [comment]
Added in commit c4feb1db2a3292e7ea24072826121641b769374f
