### ISSUE TITLE
Can't follow progress of WU bound to 1st slot

### ISSUE THREAD

**Issue by ffissore** [cdberkstresser/fah-control#5]
Jotting this down for the first one with time to address it

As you can see in the gif below, when a WU is selected as a consequence of selecting a slot, every time fahcontrol gets an update, it selects the second (last?) WU. This changes the data displayed on the right pane, and makes it impossible to follow how the WU bound to the first (non-last?) slot is going.

If you instead select the WU directly, that selection doesn't change, but you'll see the selection of slot changing on its own.

The last/non-last doubt is about me having just 2 slots, so I cannot be sure it's about the second or the last
![wu](https://user-images.githubusercontent.com/510465/79864370-a6ee5300-83d9-11ea-882b-a0d85fa8f18c.gif)

**Comment by braiam** [comment]
I've been unable to reproduce it reliably. Changing rapidly between slots seems to cause it. Maybe some race condition?

**Comment by ffissore** [comment]
Short update: after much digging, it seems the culprit is in calling `app.slot_status_list.clear()` or `app.queue_list.clear()`. With gtk2, clearing the model did **not** trigger a selection change, whereas with gtk3 it does: as the model is cleared, selection is reset.
More details as I keep on digging
