### ISSUE TITLE
Actions apply to every slot instead of just the selected one

### ISSUE THREAD

**Issue by braiam** [cdberkstresser/fah-control#7]
If I pause/fold/finish any slot, the action is applied to both instead. This wasn't present on the previous version.

**Comment by ffissore** [comment]
I tried on linux and it works for me: I can pause/fold/finish a specific slot. which OS are you using?

**Comment by braiam** [comment]
Debian sid. The logs are consistent with this behavior. 

```
00:35:03:Started thread 27 on PID 38752
00:35:13:FS00:Paused
00:35:13:FS01:Paused
```
I'm was using version 7.6.7 of the client, tried upgrading and got the same behavior.

```
00:39:41:FS00:Unpaused
00:39:41:FS00:Finishing
00:39:41:FS01:Unpaused
00:39:41:FS01:Finishing
```

Starting manager from the terminal didn't produce any log.

**Comment by ffissore** [comment]
> I'm was using version 7.6.7 of the client, tried upgrading and got the same behavior.

Do you mean that this happening with the official upstream release of fah-control? Or with this fork?

**Comment by braiam** [comment]
It happens with this fork, as official one is uninstallable due dependency issues. The client (fahclient) is the official one.

**Comment by ipkh** [comment]
It is working correctly on Xubuntu 20.04

**Comment by braiam** [comment]
I don't know how to read. I'm using the buttons besides the slider. Those apply to all slots on the client. For some reason I came to believe that those only applies to the selected slot/unit. Probably messing too much with BOINC manager.
